config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users
  resources :stores, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :staffs
  resources :reports
  resources :cases, only: [:index, :new, :edit, :create, :update, :destroy]
  # resources :scores, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  resources :jobs, only: [:index, :new, :edit, :create, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :payments, only: [:index, :edit, :create, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :ranks, only: [:index, :new, :edit, :create, :update]
  resources :bounties, only: [:index, :new, :edit, :create, :update]

  get 'about', to: 'homes#about'
  get 'history', to: 'homes#history'
  root 'homes#top'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bounty.rb
class Bounty < ApplicationRecord

  with_options presence: true do
    validates :staff_c
    validates :staff_b
    validates :staff_a
    validates :lead_b
    validates :lead_a
    validates :director
    validates :ratio
  end

end

app/models/case.rb
class Case < ApplicationRecord

  has_many :scores, inverse_of: :case, dependent: :destroy
  accepts_nested_attributes_for :scores, allow_destroy: true, reject_if: :all_blank

  belongs_to :report

  with_options presence: true do
    validates :timeframe
  end

  enum timeframe: {
    '09:00-09:59': 0,
    '10:00-10:59': 1,
    '11:00-11:59': 2,
    '12:00-12:59': 3,
    '13:00-13:59': 4,
    '14:00-14:59': 5,
    '15:00-15:59': 6,
    '16:00-16:59': 7,
    '17:00-17:59': 8,
    '18:00-18:59': 9,
    '19:00-19:59': 10,
    '20:00-20:59': 11,
    '不明／その他': 12
  }

end

app/models/job.rb
class Job < ApplicationRecord

  belongs_to :rank, optional: true
  belongs_to :staff
  belongs_to :store, optional: true
  has_one :payment, dependent: :destroy

  with_options presence: true do
    validates :staff_id
    validates :date
    validates :rank_id
    validates :time_start
    validates :time_end
  end

end

app/models/payment.rb
class Payment < ApplicationRecord

  with_options optional: true do
    belongs_to :job
    belongs_to :staff
    belongs_to :report
  end

  with_options presence: true do
    validates :date
    validates :staff_id
  end

end

app/models/rank.rb
class Rank < ApplicationRecord

  has_many :jobs
  has_many :staffs

  with_options presence: true do
    validates :name
    validates :per_hour
  end

end

app/models/report.rb
class Report < ApplicationRecord

  has_many :cases, inverse_of: :report, dependent: :destroy
  # accepts_nested_attributes_for :cases, allow_destroy: true, reject_if: :reject_case
  accepts_nested_attributes_for :cases, allow_destroy: true, reject_if: :all_blank

  has_many :scores, through: :cases
  has_many :payments

  belongs_to :user
  belongs_to :store

  with_options presence: true do
    validates :date
    validates :store_id
    validates :user_id
  end

end

app/models/score.rb
class Score < ApplicationRecord

  belongs_to :case
  # belongs_to :report, through: :case
  # has_one :report, through: :case
  belongs_to :staff

  with_options presence: true do
    validates :staff_id
    # validates :point, numericality: { greater_than: 0, less_than_or_equal_to: 1}
    validates :point, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1}
  end

end

app/models/staff.rb
class Staff < ApplicationRecord

  belongs_to :rank
  has_many :cases
  has_many :jobs
  has_many :payments

  with_options presence: true do
    validates :name
    validates :rank_id
  end

  enum rank: {
    '未設定': 0,
    Staff_C: 1,
    Staff_B: 2,
    Staff_A: 3,
    Lead_B: 4,
    Lead_A: 5,
    Director: 6
  }

end

app/models/store.rb
class Store < ApplicationRecord

  has_many :reports
  has_many :jobs

  with_options presence: true do
    validates :name
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:user_id]

  has_many :reports

  # No use email
  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end

  # account_security_level の設定
  enum account_level: {
    undefined: 0,
    director: 1,
    client: 2,
    headquarter: 3,
    headquarter_admin: 4,
    manager: 5,
    admin: 6
  }

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController

  before_action :hq_admin_level_only
  before_action :admin_only, only: [:show, :destroy]

  def index
    @staffs = Staff.all.order("id")
  end

  def show
    @staff = Staff.find(params[:id])
    @date_indicator = Date.new(2021,12,01)
  end

  def new
    @staff = Staff.new
    @ranks = Rank.all.order("per_hour")
  end

  def edit
    @staff = Staff.find(params[:id])
    @ranks = Rank.all.order("per_hour")
  end

  def create
    @staff = Staff.new(staff_params)
    if @staff.save
      redirect_to staffs_path, flash: { notice: 'スタッフ情報が追加されました。' }
    else
      flash.now[:alert] = "氏名と役職を入力してください。"
      render 'new'
    end
  end

  def update
    @staff = Staff.find(params[:id])
    if @staff.update(staff_params)
      redirect_to staffs_path, flash: { notice: 'スタッフ情報を更新しました。' }
    else
      flash.now[:alert] = "氏名と役職を確認してください。"
      render 'edit'
    end
  end

  private

  def staff_params
    params.require(:staff).permit(:name, :rank_id, :memo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bounties_helper.rb
module BountiesHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/staffs/edit.html.erb
<h1>スタッフ情報修正／削除</h1>

<%= form_with(model: @staff, local: true) do |f| %>
  <div class="field">
    <%= f.label :name, '氏名' %><br>
    <%= f.text_field :name, class: "" %>
  </div>

  <div class="field">
    <%= f.label :rank_id, '役職' %><br>
    <%#= f.select :rank, Staff.ranks.keys, {class: ""} %>
    <%= f.select :rank_id, Rank.all.order("per_hour").map { |rank| [rank.name, rank.id] }, prompt:"＊役職を選択" %>
  </div>

  <div class="field">
    <%= f.label :memo, '備考' %><br>
    <%= f.text_area :memo, class: "" %>
  </div>

  <div class="actions">
    <%= f.submit '修正' %>
    <%= f.submit '削除' %>
  </div>

<% end %>

<p class="back-to-top"><%= link_to '一覧に戻る', staffs_path %></p>

app/views/staffs/index.html.erb
<h1>スタッフ情報一覧</h1>

<div>
  <div class="staff-row">
    <span class="col-common staff-col staff-id">No.</span>
    <span class="col-common staff-col staff-name">氏名</span>
    <span class="col-common staff-col staff-rank">ランク</span>
    <span class="col-common staff-col staff-button">シフト</span>
    <span class="col-common staff-col staff-point">獲得数</span>
    <span class="col-common staff-col staff-point">獲得力/h<br><span class="fs12">(前日まで)</span></span>
  </div>
  <% @staffs.each do |s| %>
    <div class="staff-row">
      <span class="col-common staff-col staff-id"><%= s.id %>.</span>
      <span class="col-common staff-col staff-name">
        <%= link_to(edit_staff_path(s.id), class: "link_to_do_text") do %>
          <%= s.name %>
        <% end %>
      </span>
      <span class="col-common staff-col staff-rank">
        <% unless s.rank_id.nil? %>
          <%= Rank.find(s.rank_id).name %>
        <% end %>
      </span>
      <span class="col-common staff-col staff-button">
        <%= link_to 'シフト', new_job_path(staff_id: s.id), class: "staff-button-deco bg-white" %>
      </span>
      <span class="col-common staff-col staff-point">
        <%#= link_to '獲得数', staff_path(s), class: "staff-button-deco bg-light-orange" %>

        <%# report_till_yesterday = @reports.where("date < ?", Date.today) %>
        <%# report_till_yesterday.each do |ry| %>
          <%# points_sum_till_yesterday = Case.where(report_id: ry.id, staff_id: s.id).sum(:point) %>
        <%# end %>

        <% points_sum_till_yesterday = Score.where(staff_id: s.id).sum(:point) %>
        <%= points_sum_till_yesterday %>
      </span>
      <span class="col-common staff-col staff-point">
        <% js = Job.all.where("staff_id = ? and date < ?", s.id, Date.today) %>
        <% hours_so_far = ( js.pluck(:time_end).sum - js.pluck(:time_start).sum ) / 3600 - js.pluck(:time_break).sum / 60 %>
        <% unless hours_so_far == 0 || hours_so_far == nil %>
          <%= ( points_sum_till_yesterday * 1 / hours_so_far ).round(2) %>
        <% end %>
      </span>
    </div>
  <% end %>
    <span class="col-common staff-col staff-id"></span>
    <span class="col-common staff-col staff-name"></span>
    <span class="col-common staff-col staff-rank"></span>
    <span class="col-common staff-col staff-button"></span>
    <span class="col-common staff-col staff-point"></span>
    <span class="col-common staff-col staff-point"><%= link_to '新規作成', new_staff_path, class: "staff-button-deco bg-orange" %></span>
</div>

<p class="back-to-top"><%= link_to 'トップに戻る', root_path %></p>

app/views/staffs/new.html.erb
<h1>スタッフ追加</h1>

<%= form_with(model: @staff, local: true) do |f| %>
  <div class="field">
    <%= f.label :name, '氏名' %><br>
    <%= f.text_field :name, class: "" %>
  </div>

  <div class="field">
    <%= f.label :rank_id, '役職' %><br>
    <%= f.select :rank_id, Rank.all.order("per_hour").map { |rank| [rank.name, rank.id] }, prompt:"＊役職を選択" %>
  </div>

  <div class="field">
    <%= f.label :memo, '備考' %><br>
    <%= f.text_area :memo, class: "" %>
  </div>

  <div class="actions">
    <%= f.submit '追加' %>
  </div>
<% end %>

<p class="back-to-top"><%= link_to '一覧に戻る', staffs_path %></p>

app/views/staffs/show.html.erb
<h1>スタッフ獲得件数</h1>

<p><%= @staff.name %>　さん</p>

<br><br><br>

  <%# @staffs.each do |s| %>
  <% while @date_indicator.month == 12 do %>
    <div class="staff-row">
      <% if @date_indicator.wday == 6 %><span style="color: blue;"><% end %>
      <% if @date_indicator.wday == 0 || @date_indicator == Date.new(2021,11,3) || @date_indicator == Date.new(2021,11,23) %>
        <span style="color: red;">
      <% end %>
      <span class="staff-id"><%= @date_indicator.month %>/<%= @date_indicator.day %></span>
      <span class="staff-name"><%= Store.find(1).name %></span>
      <span class="staff-name"><%= Rank.find(@staff.rank_id).name %></span>
      <span class="staff-rank">
        <% rp = Report.where(store_id: 1, date: @date_indicator) %>
        <%#= Case.where(report_id: rp, staff_id: @staff.id).scores.sum(:point) %>
      </span>
      <% @date_indicator += 1 %>

      <span class="staff-button"><%#= link_to '獲得数', staff_path(s), class: "staff-button-deco bg-pink" %></span>
      <span class="staff-button"><%#= link_to 'シフト', staff_path(s), class: "staff-button-deco bg-white" %></span>
      <span class="staff-button"><%#= link_to '変更', edit_staff_path(s), class: "staff-button-deco" %></span>

      <% if @date_indicator.wday == 6 || 0 %></span><% end %>
    </div>
  <% end %>


<p class="back-to-top"><%= link_to '一覧に戻る', staffs_path %></p>