config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users
  resources :stores, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :staffs
  resources :reports
  resources :cases, only: [:index, :new, :edit, :create, :update, :destroy]
  # resources :scores, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  resources :jobs, only: [:index, :new, :edit, :create, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :payments, only: [:index, :edit, :create, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :ranks, only: [:index, :new, :edit, :create, :update]
  resources :bounties, only: [:index, :new, :edit, :create, :update]

  get 'about', to: 'homes#about'
  get 'history', to: 'homes#history'
  root 'homes#top'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bounty.rb
class Bounty < ApplicationRecord

  with_options presence: true do
    validates :staff_c
    validates :staff_b
    validates :staff_a
    validates :lead_b
    validates :lead_a
    validates :director
    validates :ratio
  end

end

app/models/case.rb
class Case < ApplicationRecord

  has_many :scores, inverse_of: :case, dependent: :destroy
  accepts_nested_attributes_for :scores, allow_destroy: true, reject_if: :all_blank

  belongs_to :report

  with_options presence: true do
    validates :timeframe
  end

  enum timeframe: {
    '09:00-09:59': 0,
    '10:00-10:59': 1,
    '11:00-11:59': 2,
    '12:00-12:59': 3,
    '13:00-13:59': 4,
    '14:00-14:59': 5,
    '15:00-15:59': 6,
    '16:00-16:59': 7,
    '17:00-17:59': 8,
    '18:00-18:59': 9,
    '19:00-19:59': 10,
    '20:00-20:59': 11,
    '不明／その他': 12
  }

end

app/models/job.rb
class Job < ApplicationRecord

  belongs_to :rank, optional: true
  belongs_to :staff
  belongs_to :store, optional: true
  has_one :payment, dependent: :destroy

  with_options presence: true do
    validates :staff_id
    validates :date
    validates :rank_id
    validates :time_start
    validates :time_end
  end

end

app/models/payment.rb
class Payment < ApplicationRecord

  with_options optional: true do
    belongs_to :job
    belongs_to :staff
    belongs_to :report
  end

  with_options presence: true do
    validates :date
    validates :staff_id
  end

end

app/models/rank.rb
class Rank < ApplicationRecord

  has_many :jobs
  has_many :staffs

  with_options presence: true do
    validates :name
    validates :per_hour
  end

end

app/models/report.rb
class Report < ApplicationRecord

  has_many :cases, inverse_of: :report, dependent: :destroy
  # accepts_nested_attributes_for :cases, allow_destroy: true, reject_if: :reject_case
  accepts_nested_attributes_for :cases, allow_destroy: true, reject_if: :all_blank

  has_many :scores, through: :cases
  has_many :payments

  belongs_to :user
  belongs_to :store

  with_options presence: true do
    validates :date
    validates :store_id
    validates :user_id
  end

end

app/models/score.rb
class Score < ApplicationRecord

  belongs_to :case
  # belongs_to :report, through: :case
  # has_one :report, through: :case
  belongs_to :staff

  with_options presence: true do
    validates :staff_id
    # validates :point, numericality: { greater_than: 0, less_than_or_equal_to: 1}
    validates :point, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1}
  end

end

app/models/staff.rb
class Staff < ApplicationRecord

  belongs_to :rank
  has_many :cases
  has_many :jobs
  has_many :payments

  with_options presence: true do
    validates :name
    validates :rank_id
  end

  enum rank: {
    '未設定': 0,
    Staff_C: 1,
    Staff_B: 2,
    Staff_A: 3,
    Lead_B: 4,
    Lead_A: 5,
    Director: 6
  }

end

app/models/store.rb
class Store < ApplicationRecord

  has_many :reports
  has_many :jobs

  with_options presence: true do
    validates :name
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:user_id]

  has_many :reports

  # No use email
  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end

  # account_security_level の設定
  enum account_level: {
    undefined: 0,
    director: 1,
    client: 2,
    headquarter: 3,
    headquarter_admin: 4,
    manager: 5,
    admin: 6
  }

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  before_action :no_director_and_no_client
  before_action :hq_admin_level_only, only: [:edit, :update]
  before_action :admin_only, only: [:destroy]

  def index
    @stores = Store.all.all.order("id")
    @reports = Report.all.order("date")
  end

  def new
    @store = Store.new
  end

  def edit
    @store = Store.find(params[:id])
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to stores_path, flash: { notice: '催事場所が新しく追加されました。' }
    else
      flash.now[:alert] = "催事場所の名称を正しく入力してください。"
      render 'new'
    end
  end

  def update
    @store = Store.find(params[:id])
    if @store.update(store_params)
      redirect_to stores_path, flash: { notice: '催事場所を修正しました。' }
    else
      flash.now[:alert] = "催事場所の名称を正しく入力してください。"
      render 'edit'
    end
  end

  def destroy
  end

  private

  def store_params
    params.require(:store).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bounties_helper.rb
module BountiesHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/edit.html.erb
<h1>催事場所修正／削除</h1>

<%= form_with(model: @store, local: true) do |f| %>
  <%= f.label :name, '催事場所の名称' %>
  <%= f.text_field :name, class: "" %>
  <%= f.submit '修正' %>
  <%= f.submit '削除' %>
<% end %>

<p class="back-to-top"><%= link_to '一覧に戻る', stores_path %></p>

app/views/stores/index.html.erb
<h1>催事場所一覧</h1>

<div>
    <div class="store-row">
      <span class="col-common store-col store-id">
        No.
      </span>
      <span class="col-common store-col store-name">
        場所名
      </span>
      <span class="col-common store-col store-button">
        変更
      </span>
    </div>
  <% @stores.each do |s| %>
    <div class="store-row">
      <span class="col-common store-col store-id">
        <%= s.id %>.
      </span>
      <span class="col-common store-col store-name">
        <%= s.name %>
      </span>
      <span class="col-common store-col store-button">
        <%= link_to '変更', edit_store_path(s), class: "store-button-deco" %>
      </span>
    </div>
  <% end %>
      <span class="col-common store-col store-id"></span>
      <span class="col-common store-col store-name"></span>
      <span class="col-common store-col store-button">
        <%= link_to '新規作成', new_store_path, class: "store-button-deco bg-orange" %>
      </span>
</div>

<p class="back-to-top"><%= link_to 'トップに戻る', root_path %></p>

app/views/stores/new.html.erb
<h1>店舗追加</h1>

<%= form_with(model: @store, local: true) do |f| %>
  <%= f.label :name, '催事場所の名称' %>
  <%= f.text_field :name, class: "" %>
  <%= f.submit '追加' %>
<% end %>

<p class="back-to-top"><%= link_to '一覧に戻る', stores_path %></p>