config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users
  resources :stores, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :staffs
  resources :reports
  resources :cases, only: [:index, :new, :edit, :create, :update, :destroy]
  # resources :scores, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  resources :jobs, only: [:index, :new, :edit, :create, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :payments, only: [:index, :edit, :create, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :ranks, only: [:index, :new, :edit, :create, :update]
  resources :bounties, only: [:index, :new, :edit, :create, :update]

  get 'about', to: 'homes#about'
  get 'history', to: 'homes#history'
  root 'homes#top'

end

app/models/job.rb
class Job < ApplicationRecord

  belongs_to :rank, optional: true
  belongs_to :staff
  belongs_to :store, optional: true
  has_one :payment, dependent: :destroy

  with_options presence: true do
    validates :staff_id
    validates :date
    validates :rank_id
    validates :time_start
    validates :time_end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :hq_admin_level_only, only: [:index, :new, :edit, :create, :update]
  before_action :admin_only, only: [:destroy]

  def index
    @q = Job.ransack(params[:q])
    # @results = @q.result.includes(:date).order("date")
    @results = @q.result.order("date")

    @date_origin = Date.new(2021,8,1)
    @staffs = Staff.order("id")
    @jobs_by_date = Job.order("date")
    @stores = Store.order("id")
  end

  def new
    @job = Job.new
    @ranks = Rank.order("per_hour")
    @staffs = Staff.all
  end

  def edit
    @job = Job.find(params[:id])
    @ranks = Rank.order("per_hour")
    @staffs = Staff.all
  end

  def create
    @@path = Rails.application.routes.recognize_path(request.referer)
    @job = Job.new(job_params)

    job_record = Job.find_by(date: job_params[:date], staff_id: job_params[:staff_id])

    if job_record.present?
      flash.now[:alert] = "勤務がすでに登録されています。更新する場合はシフト一覧から該当データを選択してください。"
      render 'new'
    else

      if @job.save
        @payment = Payment.new
        @payment.staff_id = @job.staff_id
        @payment.date = @job.date
        @payment.job_id = @job.id
        @payment.time_start = @job.time_start
        @payment.time_end = @job.time_end
        @payment.time_break = @job.time_break
        @payment.working_hours = (@job.time_end - @job.time_start) / 3600 - (@job.time_break.to_f / 60)
        @payment.per_hour = Rank.find(@job.rank_id).per_hour
        @payment.save
        if @@path[:controller] == "jobs"
          redirect_to jobs_path(@q, :'q[date_gteq' => @job.date - 3), flash: { notice: 'シフトを追加しました。' }
        elsif @@path[:controller] == "staffs"
          redirect_to new_job_path, flash: { notice: 'シフトを追加しました。' }
        end
      else
        flash.now[:alert] = "追加できませんでした。入力項目を確認してください。"
        render 'new'
      end
    end
  end

  def update
    @@path = Rails.application.routes.recognize_path(request.referer)
    @job = Job.find(params[:id]) # このidで上書きする予定。データはDBのもので、フォーム送信データを含まず。
    job_record = Job.find_by(date: job_params[:date], staff_id: job_params[:staff_id]) # 上書き前のデータ
    job_current = Job.new(job_params) # フォームからの送信データ。未保存。

    # job_recordがあるなら（日付やスタッフが元データと同じなら）
    #   job_recordのidとtparamsのidが違うなら ＝ 勝手に不本意に上書きされようとしているなら
    #     render 'edit'
    #   job_recordのidとparamsのidが同じなら ＝ 単に元のデータを修正しようとしているだけなら
    #     普通にアップデートする
    # job_recordがなければ（updateでデータが別日に移るorスタッフが変わったら）
    #   普通にアップデートする
    if job_record.nil? || job_record.id == @job.id
      if Payment.find_by(job_id: @job.id)
        @payment = Payment.find_by(job_id: @job.id)
      else
        @payment = Payment.new
      end

      @payment.staff_id = job_current.staff_id
      @payment.date = job_current.date
      @payment.job_id = job_current.id
      @payment.time_start = job_current.time_start
      @payment.time_end = job_current.time_end
      @payment.time_break = job_current.time_break
      @payment.working_hours = (job_current.time_end - job_current.time_start) / 3600 - (job_current.time_break.to_f / 60)
      @payment.per_hour = Rank.find(job_current.rank_id).per_hour

      if @job.update(job_params) && @payment.update(
        staff_id: job_current.staff_id,
        date: job_current.date,
        job_id: @job.id,
        time_start: job_current.time_start,
        time_end: job_current.time_end,
        time_break: job_current.time_break,
        working_hours: (job_current.time_end - job_current.time_start) / 3600 - (job_current.time_break.to_f / 60),
        per_hour: Rank.find(job_current.rank_id).per_hour
      )
        if @@path[:controller] == "jobs"
          redirect_to jobs_path(@q, :'q[date_gteq' => @job.date - 3), flash: { notice: 'シフトを追加しました。' }
        elsif @@path[:controller] == "staffs"
          redirect_to new_job_path, flash: { notice: 'シフトを追加しました。' }
        end
      else
        flash.now[:alert] = "修正できませんでした。入力項目を確認してください。"
        render 'edit'
      end
    else
      # flash.now[:alert] = "勤務がすでに登録されています。更新する場合はシフト一覧から該当データを選択してください。"
      # render 'edit'
      redirect_to edit_job_path(@job.id), flash: { notice: '勤務がすでに登録されています。更新する場合はシフト一覧から該当データを選択してください。' }
    end
  end

  def destroy
    @job = Job.find(params[:id])
    if @payment = Payment.find_by(job_id: @job.id).present?
      @payment = Payment.find_by(job_id: @job.id)
    end
    if @job.destroy && @payment.destroy
      redirect_to jobs_path(@q, :'q[date_gteq' => @job.date - 3), flash: { notice: 'シフトを削除しました。' }
    else
      flash.now[:alert] = "削除できませんでした。解決しない場合は管理者に連絡してください。"
      render 'edit'
    end
  end

  def search
  end

  private

  def job_params
    params.require(:job).permit(:staff_id, :date, :rank_id, :store_id, :time_start, :time_end, :time_break)
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_job_add.html.erb
  <div class="field">
    <span class="col-common form-new-left">
      <%= f.label :staff_id, '名　　前' %>
    </span>
    <span class="col-common form-new-right">
      <% if params[:staff_id] %>
        <%= f.select :staff_id, Staff.all.map { |staff| [staff.name, staff.id] }, {selected: params[:staff_id]} %>
      <% else %>
        <%= f.select :staff_id, Staff.all.map { |staff| [staff.name, staff.id] }, prompt:"＊名前を選択" %>
      <% end %>
    </span>
  </div>

  <div class="field">
    <span class="col-common form-new-left">
      <%= f.label :date, '日　　付' %>
    </span>
    <span class="col-common form-new-right">
      <% if params[:date] %>
        <%= f.date_field :date, value: params[:date] %>
      <% else %>
        <%= f.date_field :date %>
      <% end %>
    </span>
  </div>

  <div class="field">
    <span class="col-common form-new-left">
      <%= f.label :time_start, '開始時間' %>
    </span>
    <span class="col-common form-new-right">
      <%= f.time_field :time_start %>
    </span>
  </div>

  <div class="field">
    <span class="col-common form-new-left">
      <%= f.label :time_end, '終了時間' %>
    </span>
    <span class="col-common form-new-right">
      <%= f.time_field :time_end %>
    </span>
  </div>

  <div class="field">
    <span class="col-common form-new-left">
      <%= f.label :time_break, '休　　憩' %>
    </span>
    <span class="col-common form-new-right">
      <% if action_name == "new" %>
        <%= f.number_field :time_break, value: 0, class: "number_field" %> 分
      <% else %>
        <%= f.number_field :time_break, class: "number_field" %> 分
      <% end %>
    </span>
  </div>

  <div class="field">
    <span class="col-common form-new-left">
      <%= f.label :store_id, '稼働場所' %>
    </span>
    <span class="col-common form-new-right">
      <%= f.select :store_id, Store.all.map { |store| [store.name, store.id] }, prompt:"＊催事場所を選択" %>
    </span>
  </div>

  <div class="field">
    <span class="col-common form-new-left">
      <%= f.label :rank, '役　　職' %>
    </span>
    <span class="col-common form-new-right">
      <% if params[:staff_id] %>
        <%= f.select :rank_id, Rank.all.map { |rank| [rank.name, rank.id] }, {selected: Staff.find(params[:staff_id]).rank_id} %>
      <% else %>
        <%= f.select :rank_id, Rank.all.map { |rank| [rank.name, rank.id] }, prompt:"＊役職を選択" %>
      <% end %>
    </span>
  </div>

  <br>

app/views/jobs/_search.html.erb
<%= search_form_for @q, url: jobs_path do |f| %>

  <!-- 期間指定：<%#= f.date_field :date_gteq, include_blank: true %> 〜 <%#= f.date_field :date_lteq, include_blank: true %>　 -->
  開始日の指定：<%= f.date_field :date_gteq, include_blank: true %>　

  <%= f.submit '検索', class: 'bg-light-orange' %>

<% end %>

app/views/jobs/edit.html.erb
<%= form_with(model: @job, local: true) do |f| %>

  <%= render 'job_add', f: f %>

  <%= f.submit '修正' %>

<% end %>

  <% if current_user.account_level == 'manager' || current_user.account_level == 'admin' %>
    <br>
    <%= link_to '(削除)', job_path(@job.id), method: :delete, data: { confirm: "勤務を削除すると保存されている給与情報も一緒に削除されます。\n本当に削除してよろしいですか？\n　　名前：" + Staff.find(@job.staff_id).name+"\n　　日付：" + @job.date.strftime("%Y/%m/%d") + "\n削除する場合は「OK」、やめる場合は「キャンセル」を選択してください。" }, class: "fs12 bg-pink" %>
  <% end %>

<p class="back-to-top"><%= link_to 'シフト一覧に戻る', jobs_path(@q, :'q[date_gteq' => @job.date - 3) %></p>

<p class="back-to-top"><%= link_to 'スタッフ一覧に戻る', staffs_path %></p>

app/views/jobs/index.html.erb
<h1>シフト管理</h1>

<p class="page-desription">シフト一覧です。遅くとも当日朝までには入力してください。（時間と役職は後からでも修正できます）
</p>

<div class="search-form">
  <%= render 'search', q: @q, url: jobs_path %>
</div>

<div class="job-arrow-area cf">
  <span class="staff-button">
    <%= link_to '◀︎ 前の週へ', jobs_path(@q, :'q[date_gteq' => "#{@q.date_gteq}".to_date - 7), class: "staff-button-deco float_left fs14" %>
  </span>
  <span class="staff-button">
    <%= link_to '次の週へ ▶︎', jobs_path(@q, :'q[date_gteq' => "#{@q.date_gteq}".to_date + 7), class: "staff-button-deco float_right fs14" %>
  </span>
</div>

<div class="test0 if_width_too_narrow">

  <% if params[:q].present? && params[:q].values.first.present? %>
    <% date_first = params[:q].values.first.to_date %>
    <% date_last = params[:q].values.last.to_date + 6 %>
  <% else %>
      <% date_first = Date.current %>
      <% date_last = Date.current + 6 %>
  <% end %>


  <span class="staff-button">
    <%= link_to '新規作成', new_job_path(date: @q.date_gteq), class: "staff-button-deco bg-orange" %>
  </span><br>
  <br><br>

  <!-- 日付の欄 -->
  <div class="test0">
    <span class="test1">
    </span>

    <% for d in date_first..date_last do %>
      <span class="test1">
        <%= d.strftime("%m/%d(#{@wd[d.wday]})") %>
      </span>
    <% end %>
  </div>


  <!-- スタッフシフトの欄 -->
  <% if @staffs.exists? %>

    <% i = 0 %>
    <% while i < @staffs.count %>
      <% i += 1 %>

      <div class="test0">
        <%= link_to(edit_staff_path(i), class: "btn-job-name") do %>
          <span class="test1">
            <p class="fs14">
              <%= @staffs.find(i).name %>
            </p>
          </span>
        <% end %>

        <% for d in date_first..date_last do %>
          <% job_spot = @jobs_by_date.find_by(staff_id: i, date: d) %>

          <% if job_spot.nil? %>
            <%= link_to(new_job_path(staff_id: i, date: d), class: "btn-job-spot") do %>
              <span class="test1">
                <p style="line-height: 55px; font-size: 11px;">
                  (追加)
                </p>
              </span>
            <% end %>
          <% else %>
            <%= link_to(edit_job_path(job_spot.id), class: "btn-job-spot") do %>
              <span class="test1 bg-light-orange">
                <p class="fs14">
                  <%= job_spot.time_start.strftime("%H:%M") %>-<%= job_spot.time_end.strftime("%H:%M") %>
                </p>
                <p class="fs12">　
                  <% unless job_spot.time_break == 0 || job_spot.time_break == nil %>
                    (休憩 <%= job_spot.time_break %>分)
                  <% end %>　
                </p>
                <p class="fs12">
                  <% unless job_spot.store_id.nil? %>
                    <%= @stores.find(job_spot.store_id).name %>
                  <% end %>
                </p>
                <p class="fs12">
                  <% unless job_spot.rank_id.nil? %>
                    <%= Rank.find(job_spot.rank_id).name %>
                  <% end %>
                </p>
              </span>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>

</div>

<!-- <div id="sp-only">
  <p class="fs12">こちらはPCでのご利用をお願いいたします <i class="far fa-sad-tear"></i></p>
</div> -->

<p class="back-to-top"><%= link_to 'トップに戻る', root_path %></p>

app/views/jobs/index_search.html.erb
<h1>シフト管理</h1>

<p class="page-desription">シフト一覧です。遅くとも当日朝までには入力してください。（時間と役職は後からでも修正できます）
</p>

<div class="search-form">
  <%= render 'search', q: @q, url: jobs_path %>
</div>

<div class="test0">

  <% if params[:q].present? %>
    <% if params[:q].values.first.present? %>
      <% date_first = params[:q].values.first.to_date %>
    <% else %>
      <% date_first = @date_origin %>
    <% end %>

    <% if params[:q].values.last.present? %>
      <% date_last = params[:q].values.last.to_date %>
    <% else %>
      <% date_last = @jobs_by_date.last.date.next_month.end_of_month if @jobs_by_date %>
    <% end %>
  <% else %>
    <%# date_first = @date_origin %>
    <% date_first = Date.current.beginning_of_month %>
    <% if @jobs_by_date.present? %>
      <% date_last = @jobs_by_date.last.date.next_month.end_of_month %>
    <% else %>
      <% date_last = @date_origin.next_month.end_of_month %>
    <% end %>
  <% end %>


  <span class="staff-button">
    <%= link_to '新規作成', new_job_path, class: "staff-button-deco bg-orange" %>
  </span><br>

  <br><br>

  <% if @results.exists? %>
    <div class="test0">
      <span class="test1">
      </span>

      <% for d in date_first..date_last do %>
        <span class="test1">
          <%= d.strftime("%m/%d(#{@wd[d.wday]})") %>
        </span>
      <% end %>
    </div>


    <% i = 0 %>
    <% while i < @staffs.count %>
      <% i += 1 %>

      <div class="test0">
            <%= link_to(edit_staff_path(i), class: "btn-job-name fs12") do %>
              <span class="test1">
                <p class="fs14">
                  <%= @staffs.find(i).name %>
                </p>
              </span>
            <% end %>

        <% for d in date_first..date_last do %>
          <% job_spot = @jobs_by_date.find_by(staff_id: i, date: d) %>

          <% if job_spot.nil? %>
            <%= link_to(new_job_path(staff_id: i, date: d), class: "btn-job-spot fs12") do %>
              <span class="test1">
                <p style="line-height: 55px;">
                  (追加)
                </p>
              </span>
            <% end %>
          <% else %>
            <%= link_to(edit_job_path(job_spot.id), class: "btn-job-spot fs12 bg-light-orange") do %>
              <span class="test1">
                <p class="fs14">
                  <%= job_spot.time_start.strftime("%H:%M") %>-<%= job_spot.time_end.strftime("%H:%M") %>
                </p>
                <p class="fs12">　
                  <% unless job_spot.time_break == 0 || job_spot.time_break == nil %>
                    (休憩 <%= job_spot.time_break %>分)
                  <% end %>　
                </p>
                <p class="fs12">
                  <% unless job_spot.store_id.nil? %>
                    <%= @stores.find(job_spot.store_id).name %>
                  <% end %>
                </p>
                <p class="fs12">
                  <% unless job_spot.rank_id.nil? %>
                    <%= Rank.find(job_spot.rank_id).name %>
                  <% end %>
                </p>
              </span>
            <% end %>
          <% end %>

        <% end %>
      </div>
    <% end %>
  <% end %>

</div>


<p class="back-to-top"><%= link_to 'トップに戻る', root_path %></p>

app/views/jobs/new.html.erb
<%= form_with(model: @job, local: true) do |f| %>

  <%= render 'job_add', f: f %>

  <%= f.submit '作成' %>

<% end %>

<p class="back-to-top">
  <% if params[:date].present? %>
    <%= link_to 'シフト一覧に戻る', jobs_path(@q, :'q[date_gteq' => params[:date].to_date - 3) %>
  <% else %>
    <%= link_to 'シフト一覧に戻る', jobs_path(@q, :'q[date_gteq' => Date.current) %>
  <% end %>
  <br>
  <%= link_to 'スタッフ一覧に戻る', staffs_path %>
</p>