config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users
  resources :stores, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :staffs
  resources :reports
  resources :cases, only: [:index, :new, :edit, :create, :update, :destroy]
  # resources :scores, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  resources :jobs, only: [:index, :new, :edit, :create, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :payments, only: [:index, :edit, :create, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :ranks, only: [:index, :new, :edit, :create, :update]
  resources :bounties, only: [:index, :new, :edit, :create, :update]

  get 'about', to: 'homes#about'
  get 'history', to: 'homes#history'
  root 'homes#top'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bounty.rb
class Bounty < ApplicationRecord

  with_options presence: true do
    validates :staff_c
    validates :staff_b
    validates :staff_a
    validates :lead_b
    validates :lead_a
    validates :director
    validates :ratio
  end

end

app/models/case.rb
class Case < ApplicationRecord

  has_many :scores, inverse_of: :case, dependent: :destroy
  accepts_nested_attributes_for :scores, allow_destroy: true, reject_if: :all_blank

  belongs_to :report

  with_options presence: true do
    validates :timeframe
  end

  enum timeframe: {
    '09:00-09:59': 0,
    '10:00-10:59': 1,
    '11:00-11:59': 2,
    '12:00-12:59': 3,
    '13:00-13:59': 4,
    '14:00-14:59': 5,
    '15:00-15:59': 6,
    '16:00-16:59': 7,
    '17:00-17:59': 8,
    '18:00-18:59': 9,
    '19:00-19:59': 10,
    '20:00-20:59': 11,
    '不明／その他': 12
  }

end

app/models/job.rb
class Job < ApplicationRecord

  belongs_to :rank, optional: true
  belongs_to :staff
  belongs_to :store, optional: true
  has_one :payment, dependent: :destroy

  with_options presence: true do
    validates :staff_id
    validates :date
    validates :rank_id
    validates :time_start
    validates :time_end
  end

end

app/models/payment.rb
class Payment < ApplicationRecord

  with_options optional: true do
    belongs_to :job
    belongs_to :staff
    belongs_to :report
  end

  with_options presence: true do
    validates :date
    validates :staff_id
  end

end

app/models/rank.rb
class Rank < ApplicationRecord

  has_many :jobs
  has_many :staffs

  with_options presence: true do
    validates :name
    validates :per_hour
  end

end

app/models/report.rb
class Report < ApplicationRecord

  has_many :cases, inverse_of: :report, dependent: :destroy
  # accepts_nested_attributes_for :cases, allow_destroy: true, reject_if: :reject_case
  accepts_nested_attributes_for :cases, allow_destroy: true, reject_if: :all_blank

  has_many :scores, through: :cases
  has_many :payments

  belongs_to :user
  belongs_to :store

  with_options presence: true do
    validates :date
    validates :store_id
    validates :user_id
  end

end

app/models/score.rb
class Score < ApplicationRecord

  belongs_to :case
  # belongs_to :report, through: :case
  # has_one :report, through: :case
  belongs_to :staff

  with_options presence: true do
    validates :staff_id
    # validates :point, numericality: { greater_than: 0, less_than_or_equal_to: 1}
    validates :point, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1}
  end

end

app/models/staff.rb
class Staff < ApplicationRecord

  belongs_to :rank
  has_many :cases
  has_many :jobs
  has_many :payments

  with_options presence: true do
    validates :name
    validates :rank_id
  end

  enum rank: {
    '未設定': 0,
    Staff_C: 1,
    Staff_B: 2,
    Staff_A: 3,
    Lead_B: 4,
    Lead_A: 5,
    Director: 6
  }

end

app/models/store.rb
class Store < ApplicationRecord

  has_many :reports
  has_many :jobs

  with_options presence: true do
    validates :name
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:user_id]

  has_many :reports

  # No use email
  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end

  # account_security_level の設定
  enum account_level: {
    undefined: 0,
    director: 1,
    client: 2,
    headquarter: 3,
    headquarter_admin: 4,
    manager: 5,
    admin: 6
  }

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  before_action :hq_admin_level_only, only: [:history]

  def top
    @user = current_user
    @report_today = Report.find_by(user_id: @user, date: Date.current)
    @report_today_draft = Report.find_by(user_id: @user, date: Date.current, is_submitted: false)
  end

  def about
    @reports = Report.order(date: "DESC")
  end

  def history
  end

end

app/helpers/bounties_helper.rb
module BountiesHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/homes/about.html.erb
<h1>このサイトの説明</h1>


<div class="homes_about">
  <h3>OniGOキャンペーンの結果報告を報告するサイトです</h3>


  <h3>1日の報告の流れ</h3>

  <h4>1. 開始報告をする</h4>
  <p>その日のキャンペーンが始まったら開始報告をしてください。報告当日の日付とイベント実施場所を選択して、登録ボタンを押すだけです。</p>

  <h4>2. 獲得速報をする</h4>
  <p>契約が決まったら1件ごとに速報を送ってください。獲得した時間帯やスタッフ名と、必要に応じて契約したお客様の氏名や備考欄（キャンペーン適用済み等）を記入します。送信ボタンを押せば登録完了します。<br>
  <br>
  獲得1件を複数人に分配する場合は追加ボタンを押し、スコアを合計1.0になるように配分してください。例えば1件を7:3に分ける場合は、Aさんに0.7、Bさんに0.3、と入力します。この分配方法は事前にキャンペーン責任者（大井さん）と相談し、許可がおりた現場や日程のみ行うことができます。
  </p>

  <h4>3. 実施報告をする</h4>
  <p>1日の勤務が終了したら実施報告を送ってください。実施報告画面には今まで送った速報のデータが表示されているので相違ないか確認し、必要に応じて獲得時間やスタッフ欄を修正します。獲得件数が足りない場合は、新たにトップ画面から速報を追加してください。獲得件数が多い場合は三角ボタンを押すと閉じることができます。<br>
  <br>
  画面をスクロールするとアンケートの入力ができます。該当する欄に数字を入れ、コメントがあればフリーコメントの部分に記入してください。紙の報告書と同じフォーマットです。<br>
  <br>
  そのままページ一番下の更新ボタンを押すと一時保存ができます。催事中に件数を確認したりメモをしておくのにご利用ください。再開する場合はトップ画面の実施報告ボタンを押してください。<br>
  <br>
  入力し終わったら、「実績報告を提出する場合は・・・」にチェックを入れて更新してください。更新したら報告は完了です。お疲れ様でした。
</p>


<br><br><br><br><br><br>

  <% if current_user.account_level == "manager" || current_user.account_level == "admin" %>
    サイトから直接データを追加できない場合はこちら

    <h2>サイトマップ</h2>
    <h4>
      <%= link_to(new_store_path, class: "home_button_deco bg-light-orange") do %>
        <i class="fas fa-store"></i>催事場所を追加
      <% end %>
    </h4>

    <h4>
      <%= link_to(new_staff_path, class: "home_button_deco bg-light-orange") do %>
        <i class="fas fa-user-friends"></i>スタッフを追加
      <% end %>
    </h4>

    <h4>
      <%= link_to(new_rank_path, class: "home_button_deco bg-light-orange") do %>
        <i class="fas fa-graduation-cap"></i>役職を追加
      <% end %>
    </h4>

    <h4>
      <%= link_to(bounties_path, class: "home_button_deco bg-light-orange") do %>
        <i class="fas fa-dollar-sign"></i>インセン表
      <% end %>
    </h4>

    <h4 class="cf">
      <%= link_to(new_store_path, class: "home_button_deco bg-light-orange") do %>
        <i class="fas fa-store"></i>催事場所を追加
      <% end %>
      <%# end %>
    </h4>

    <h4 class="cf">
      <%= link_to(new_case_path, class: "home_button_deco bg-light-orange") do %>
        <!-- <i class="fas fa-store"></i> -->★新規獲得★
      <% end %>
      <%# end %>
    </h4>


<br><br><br><br><br><br>

    <h2>データ表示</h2>
    <h4>報告一覧</h4>
    <h5>
      <% @reports.each do |r| %>
        <%= link_to '編集', edit_report_path(r.id), class: "home_button_edit" %>　
        <%= link_to '削除', report_path(r.id), method: :delete, data: { confirm: "報告を削除すると今まで保存された獲得件数も一緒に削除されます。\nよろしいですか？\n削除する場合は「OK」、やめる場合は「キャンセル」を選択してください。" }, class: "fs12 bg-pink" %>　
        <%= r.date %>　
        by <%= User.find(r.user_id).name %><br>
      <% end %>
    </h5>

  <% end %>

</div>

<p class="back-to-top"><%= link_to 'トップに戻る', root_path %></p>

app/views/homes/history.html.erb
<h1>更新履歴</h1>

<div class="homes_history">

  <p>
    2022.02.06　ver 1. 0.10　内部処理を改良<span style="display:none;"> (f6b1260 on master)</span><br>
    2022.01.24　ver 1. 0. 9　「困ったときは」ページに管理者が操作できる項目を追加<span style="display:none;"> (5bb34b2 on master)</span><br>
    2022.01.24　ver 1. 0. 9　シフトページの表記を改良<span style="display:none;"> (81d8ac6 on master)</span><br>
    2022.01.19　ver 1. 0. 8　給与一覧ページの表記を改良<span style="display:none;"> (941d579 on master)</span><br>
    2022.01.17　ver 1. 0. 7　給与一覧ページを前月や翌月に移動するボタンを追加<span style="display:none;"> (4fff1ed on master)</span><br>
    2022.01.13　ver 1. 0. 6　シフト作成時や更新時のページ遷移を変更<span style="display:none;"> (db81e10 on master)</span><br>
    2022.01.05　ver 1. 0. 5　報告一覧のページレイアウトを変更<span style="display:none;"> (a04a500 on master)</span><br>
    2022.01.05　ver 1. 0. 4　シフト一覧の表記を7日ごとに変更<span style="display:none;"> (277293f on master)</span><br>
    2022.01.03　ver 1. 0. 3　人件費管理の不具合を修正<span style="display:none;"> (e548d9c on master)</span><br>
    2022.01.03　ver 1. 0. 2　クライアントページのデザインを変更<span style="display:none;"></span><br>
    2021.12.16　ver 1. 0. 1　ページごとのアクセス権限を強化、ログイン画面修正<span style="display:none;"> (e3a124b on master)</span><br>
    2021.12.14　ver 1. 0. 0　β版リリース<span style="display:none;"> (0ac33e3 on master)</span>
  </p>

</div>

<p class="back-to-top"><%= link_to 'トップに戻る', root_path %></p>

app/views/homes/top.html.erb
<h1>OniGOレポ</h1>



<p class="top-button-description">
  <% if user_signed_in? %>
    <B><%= @user.name %></B>　さん。今日もお疲れさまです <i class="far fa-grin-beam"></i>
  <% end %>
</p>



<% if current_user.account_level == "director" || current_user.account_level == "headquarter_admin" || current_user.account_level == "manager" || current_user.account_level == "admin" %>
  <% if @report_today.nil? %>
    <%= link_to '開始報告', new_report_path, class: 'top-button fs22 bg-pink' %>
      <p class="top-button-description"><i class="fas fa-info-circle"></i> イベント報告をする店舗を登録してください。登録すると獲得報告を送ることができます。</p>
  <% elsif @report_today_draft.present? %>
    <%= link_to '獲得速報', new_case_path, class: 'top-button fs22 bg-orange' %>
      <p class="top-button-description"><i class="fas fa-info-circle"></i> 契約が決まったら1件ごとに獲得報告をしてください。（当日のみ報告可）</p>
    <%= link_to '実施報告', edit_report_path(@report_today), class: 'top-button fs22 bg-light-orange' %>
      <p class="top-button-description"><i class="fas fa-info-circle"></i> 1日の催事が終わったら実施報告をお願いします。（一時保存可。当日分のみ報告可）</p>
  <% end %>

  <%= link_to '報告一覧', reports_path, class: 'top-button fs22' %>
  <p class="top-button-description"><i class="fas fa-info-circle"></i> 自分が提出した報告書一覧です。過去の未提出報告書もこちらから確認できます。
    <% if @report_unsubmitted.present? %>
      <br><span class="" style="color: red;"><b>未提出の報告書があります。</b></span>
    <% end %>
  </p>
<% end %>



<% if current_user.account_level == "client" || current_user.account_level == "manager" || current_user.account_level == "admin" %>
  <h4>＜クライアントメニュー＞</h4>

  <%= link_to '催事報告', cases_path, class: 'top-button fs22 bg-orange' %>
  <p class="top-button-description"><i class="fas fa-info-circle"></i> 獲得状況の一覧を表示します。何かコメントがあればこちらからお願いいたします。</p>
<% end %>



<% if current_user.account_level == "headquarter" || current_user.account_level == "headquarter_admin" || current_user.account_level == "manager" || current_user.account_level == "admin" %>
  <h4>＜管理者用メニュー＞</h4>

  <%= link_to '催事場所管理', stores_path, class: 'top-button fs22 bg-white' %>
  <p class="top-button-description"><i class="fas fa-info-circle"></i> 催事場所の追加や編集を行います。新規の場合は必ず実施の前日までに追加してください。</p>
<% end %>

<% if current_user.account_level == "headquarter_admin" || current_user.account_level == "manager" || current_user.account_level == "admin" %>
  <%= link_to 'スタッフ管理', staffs_path, class: 'top-button fs22 bg-white' %>
  <p class="top-button-description"><i class="fas fa-info-circle"></i> スタッフの追加、編集を行います。</p>

  <%= link_to 'シフト入力', jobs_path(@q, :'q[date_gteq' => Date.current), class: 'top-button fs22 bg-white' %>
  <p class="top-button-description"><i class="fas fa-info-circle"></i> シフトの追加、編集を行います。</p>

  <%#= link_to '実績一覧', root_path, class: 'top-button fs22 bg-pink' %>
  <!-- <p class="top-button-description"><i class="fas fa-info-circle"></i> 店舗ごとの累計獲得数など実績を確認します。</p> -->

  <%= link_to '人件費管理', payments_path(@q, :'q[date_gteq' => Date.current.beginning_of_month, :'q[date_lteq' => Date.current.end_of_month), class: 'top-button fs22 bg-pink' %>
  <p class="top-button-description"><i class="fas fa-info-circle"></i> スタッフごとの獲得実績や、日当・インセンティブなど支払い額を確認します。（PC専用）</p>
<% end %>

<% if current_user.account_level == "manager" || current_user.account_level == "admin" %>
  <p class="top-button-description">インセンティブの修正は<%= link_to 'こちら', bounties_path %></p>

  <p class="top-button-description">役職の修正は<%= link_to 'こちら', ranks_path %></p>

  <p class="top-button-description">更新履歴は<%= link_to 'こちら', history_path %></p>
<% end %>

<p class="top-button-description">困ったときは<%= link_to 'こちら', about_path %></p>

<p class="top-button-description">ログアウトは<%= link_to 'こちら', destroy_user_session_path, method: :delete %></p>